"""JAEWOO Pump Intelligence System - 중앙 스타일 관리.

색상 상수, QSS 스타일시트, 브랜딩 상수 제공.
"""

# ── 상태 색상 ──────────────────────────────────────────────
STATUS_COLORS = {
    "정상":       {"bg": "#E8F5E9", "border": "#4CAF50", "text": "#1B5E20"},
    "경고":       {"bg": "#FFF3E0", "border": "#FF9800", "text": "#E65100"},
    "위험":       {"bg": "#FFEBEE", "border": "#F44336", "text": "#B71C1C"},
    "데이터부족": {"bg": "#F5F5F5", "border": "#BDBDBD", "text": "#616161"},
}

# 판정 → KPI 카테고리 매핑
JUDGMENT_TO_STATUS = {
    "정상": "정상",
    "경과관찰": "경고",
    "점검권장": "위험",
    "정밀점검": "위험",
    "데이터부족": "데이터부족",
    "데이터없음": "데이터부족",
    "분석오류": "데이터부족",
    "기준 없음": "데이터부족",
}

# 판정 → 카드 색상 매핑
JUDGMENT_CARD_COLORS = {
    "정상":       {"bg": "#E8F5E9", "border": "#2E7D32", "text": "#2E7D32", "badge": "#2E7D32"},
    "경과관찰":   {"bg": "#FFF8E1", "border": "#F57F17", "text": "#E65100", "badge": "#E65100"},
    "점검권장":   {"bg": "#FFF3E0", "border": "#EF6C00", "text": "#E65100", "badge": "#EF6C00"},
    "정밀점검":   {"bg": "#FFEBEE", "border": "#C62828", "text": "#B71C1C", "badge": "#C62828"},
    "기준 없음":  {"bg": "#F5F5F5", "border": "#757575", "text": "#616161", "badge": "#757575"},
    "데이터부족": {"bg": "#F5F5F5", "border": "#757575", "text": "#616161", "badge": "#757575"},
    "데이터없음": {"bg": "#EEEEEE", "border": "#9E9E9E", "text": "#757575", "badge": "#9E9E9E"},
}

# 역할 뱃지 색상
ROLE_BADGE_COLORS = {
    "main":  {"bg": "#1565C0", "text": "#FFFFFF"},
    "timer": {"bg": "#6A1B9A", "text": "#FFFFFF"},
    "assist": {"bg": "#00695C", "text": "#FFFFFF"},
}

# 수치 표시용 고정폭 폰트
FONT_MONO = "Consolas"

# ── 브랜딩 상수 ────────────────────────────────────────────
APP_TITLE = "JAEWOO Pump Intelligence System"
APP_VERSION = "v4.6"
WATERMARK_TEXT = "재우 내부 보고서 시스템 v2.0"
REPORT_FOOTER = "Generated by PumpReporter"
REPORT_FILENAME_PREFIX = "JAEWOO"

# ── 폰트 상수 ──────────────────────────────────────────────
FONT_FAMILY = "맑은 고딕"
FONT_SIZE_NORMAL = 9
FONT_SIZE_TITLE = 16
FONT_SIZE_CARD_TITLE = 11
FONT_SIZE_KPI = 24


# ── QSS 스타일시트 ─────────────────────────────────────────
def get_light_stylesheet() -> str:
    return """
    QMainWindow { background-color: #FAFAFA; }
    QTabWidget::pane { border: 1px solid #E0E0E0; background: #FFFFFF; }
    QTabBar::tab {
        padding: 8px 16px; font-size: 10pt;
        border: 1px solid #E0E0E0; border-bottom: none;
        background: #F5F5F5; margin-right: 2px;
    }
    QTabBar::tab:selected {
        background: #2196F3; color: white;
        border-radius: 4px 4px 0 0;
    }
    QGroupBox {
        font-weight: bold; border: 1px solid #E0E0E0;
        border-radius: 6px; margin-top: 8px; padding-top: 16px;
    }
    QGroupBox::title {
        subcontrol-origin: margin; left: 12px; padding: 0 4px;
    }
    QPushButton {
        padding: 6px 14px; border-radius: 4px;
        border: 1px solid #BDBDBD; background: #FAFAFA;
    }
    QPushButton:hover { background: #E0E0E0; }
    QTableWidget {
        gridline-color: #E0E0E0;
        alternate-background-color: #F5F5F5;
        selection-background-color: #BBDEFB;
    }
    QHeaderView::section {
        background-color: #F5F5F5; padding: 4px;
        border: 1px solid #E0E0E0; font-weight: bold;
    }
    QScrollArea { border: none; }
    """


def get_dark_stylesheet() -> str:
    return """
    QMainWindow { background-color: #303030; color: #E0E0E0; }
    QWidget { background-color: #424242; color: #E0E0E0; }
    QTabWidget::pane { border: 1px solid #555; background: #424242; }
    QTabBar::tab {
        padding: 8px 16px; font-size: 10pt;
        color: #E0E0E0; background: #505050;
        border: 1px solid #555; margin-right: 2px;
    }
    QTabBar::tab:selected { background: #1976D2; color: white; }
    QGroupBox {
        font-weight: bold; border: 1px solid #555;
        border-radius: 6px; margin-top: 8px;
        padding-top: 16px; color: #E0E0E0;
    }
    QTableWidget {
        gridline-color: #555;
        alternate-background-color: #4A4A4A;
        background-color: #424242; color: #E0E0E0;
        selection-background-color: #1565C0;
    }
    QHeaderView::section {
        background-color: #505050; padding: 4px;
        border: 1px solid #555; font-weight: bold; color: #E0E0E0;
    }
    QLineEdit, QSpinBox, QDoubleSpinBox, QComboBox, QDateEdit, QTextEdit {
        background-color: #555; color: #E0E0E0;
        border: 1px solid #777; border-radius: 3px;
    }
    QPushButton {
        padding: 6px 14px; border-radius: 4px;
        background-color: #555; color: #E0E0E0; border: 1px solid #777;
    }
    QPushButton:hover { background-color: #666; }
    QScrollArea { border: none; background-color: #424242; }
    QLabel { background-color: transparent; }
    """
